project/cart/urls.py
from django.conf.urls import url, include

from django.contrib.auth import views
from . import views
from django.contrib.auth import views as auth_views




from django.urls import path


app_name = "cart"
urlpatterns = [
	path('', views.add_to_cart, name='add_to_cart'),

	path('cart-checkout/', views.cart_checkout, name='cart_checkout'),
	path('cart-delete/<slug:id>/', views.delete_cart, name='delete_cart'),
	path('cart-change/<slug:data>/', views.change_cart, name='change_cart'),






]

project/index/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views
from . import views
from django.urls import path


app_name = "index"
urlpatterns = [
	path('', views.index, name='index'),
	path('allcategories/', views.allcategories, name='allcategories'),
	path('category/<slug:id>/', views.category, name='category'),
	path('featured-products/', views.featuredProducts, name='featuredProducts'),
	path('todays-deal/', views.todays_deal, name='todays_deal'),
	path('bundled-products/', views.bundledProducts, name='bundledProducts'),
	path('classified-ads/', views.classified_ads, name='classified_ads'),
	path('allbrands/', views.allbrands, name='allbrands'),
	path('allvendors/', views.allvendors, name='allvendors'),
	path('all-vendors-location/', views.all_vendors_location, name='all_vendors_location'),
	path('blog/', views.blog, name='blog'),
	path('contact-us/', views.contact_us, name='contact_us'),
	path('filter-items/', views.filter_items, name='filter_items'),
	path('filtered-items/', views.other_filtered_items, name='other_filtered_items'),








]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
	path('account/', include('account.urls')),
    path('administrator/', include('administrator.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),



]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

project/templates/all_vendors_location.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}


{% endblock %}

project/templates/allbrands.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<style>
	body{
		background-color: rgb(245, 245, 245)
	}
</style>

<body>
<div class="container">
	<div class="row">
		{% for i in category %}
			<div class="col-md-3" style="margin-bottom: 20px;">
				<div class="card">
				<div class="card-header">{{i}}</div>
				{% for a in brand %}
				{% if a.category == i %}
				<div class="card-body"><img src="{{a.image.url}}" alt="image" height="50px" width="50px">  {{a}}</div> 
				{% endif %}
				{% endfor %}
				
				</div>
			</div>
		{% endfor %}
	</div>
</div>
</body>
{% endblock %}

project/templates/allcategories.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
	<div class="row">
	{% for i in category %}
		<div class="col-md-3 col-sm-6" style="margin-bottom: 20px;">
			<div class="card" style="">
			<div class="card-header">
			<a href="{% url 'index:category' i.id %}"> {{i.name}} </a>
			</div>
			<ul class="list-group list-group-flush">
			{% for a in subcategory %}
			{% if a.category == i %}<li class="list-group-item"> {{a}} </li>{% endif %}
			{% endfor %}
			<li class="list-group-item">Dapibus ac facilisis in</li>
			<li class="list-group-item">Vestibulum at eros</li>
			</ul>
			</div>

		</div>
	{% endfor %}
	</div>
</div>

{% endblock %}

project/templates/allvendors.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}


{% endblock %}

project/templates/blog.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}


{% endblock %}

project/templates/carousel.html
<div id="demo" class="carousel slide" data-ride="carousel">
<ul class="carousel-indicators">
<li data-target="#demo" data-slide-to="0" class="active"></li>
<li data-target="#demo" data-slide-to="1"></li>
<li data-target="#demo" data-slide-to="2"></li>
</ul>
<div class="carousel-inner">
<!--     <div class="carousel-item active">
<img src="{% static 'img/1.JPG' %}" class="img-fluid" alt="Los Angeles">
<div class="carousel-caption">

</div>   
</div> -->
<div class="carousel-item active">
<img src="{% static 'img/2.jpg' %}" alt="Chicago" class="img-fluid">
<div class="carousel-caption">
<!--         <h3>Chicago</h3>
<p>Thank you, Chicago!</p> -->
</div>   
</div>




<div class="carousel-item">
<img src="{% static 'img/5.jpg' %}" alt="New York" class="img-fluid"">
<div class="carousel-caption">
<!--         <h3>New York</h3>
<p>We love the Big Apple!</p> -->
</div>   
</div>

<div class="carousel-item">
<img src="{% static 'img/6.jpg' %}" alt="New York" class="img-fluid">
<div class="carousel-caption">
<!--         <h3>New York</h3>
<p>We love the Big Apple!</p> -->
</div>   
</div>

<div class="carousel-item">
<img src="{% static 'img/7.jpg' %}" alt="New York" class="img-fluid">
<div class="carousel-caption">
<!--         <h3>New York</h3>
<p>We love the Big Apple!</p> -->
</div>   
</div>

<div class="carousel-item">
<img src="{% static 'img/8.jpg' %}" alt="New York" class="img-fluid">
<div class="carousel-caption">
<!--         <h3>New York</h3>
<p>We love the Big Apple!</p> -->
</div>   
</div>

<div class="carousel-item">
<img src="{% static 'img/9.jpg' %}" alt="New York" class="img-fluid">
<div class="carousel-caption">
<!--         <h3>New York</h3>
<p>We love the Big Apple!</p> -->
</div>   
</div>

<div class="carousel-item">
<img src="{% static 'img/10.jpg' %}" alt="New York" class="img-fluid">
<div class="carousel-caption">
<!--         <h3>New York</h3>
<p>We love the Big Apple!</p> -->
</div>   
</div>

</div>
<a class="carousel-control-prev" href="#demo" data-slide="prev">
<span class="carousel-control-prev-icon"></span>
</a>
<a class="carousel-control-next" href="#demo" data-slide="next">
<span class="carousel-control-next-icon"></span>
</a>
</div>
          

project/templates/classified_ads.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}

<div class="container">
	<div class="row">
		<div class="col-md-3">
			<h6>ADVANCED SEARCH</h6>
   <div class="list-group list-group-flush">

      <ul class="list-group list-group-flush">
     

	<li class="list-group-item px-0">
		<small>
	<div class="form-group">
	<label for="sel1">ALL CATEGORIES:</label>
	<select class="form-control" id="selectcategory">
	<option>ALL CATEGORIES</option>
	{% for i in category %}

	<option>{{i}}</option>
	
	{% endfor %}
	</select>
	</div>
	</small>

	<div class="form-group">
	<small>
	<label for="sel1">ALL CATEGORIES:</label>
	<select class="form-control" id="selectsubcategory">
	<option>ALL SUB CATEGORIES</option>
	</select>
	</small>
	</div>

<small>
<div class="form-group">
<label for="sel1">ALL BRANDS:</label>
<select class="form-control" id="selectbrandcategory">
<option>ALL BRANDS</option>
</select>
</div>
</small>

	<small>
	<div class="form-group">
	<input type="text" value="what are you looking for" class="form-control" name="">
	</div>
	</small>


		<small>
		<div class="form-group">
		<label for="selectpostcode">Minimum Price</label>
		<div class="slidecontainer">
		<input type="range" min="1" max="100000000" value="50" class="slider" id="myRange">
		<p>Value: <span id="demoslide"></span></p>
		</div>
		</div>
		</small>

		<small>
		<div class="form-group">
  <label for="selectpostcode">Maximum Price</label>
  <div class="slidecontainer">
  <input type="range" min="1" max="100000000" value="50" class="slider" id="myRange2">
  <p>Value: <span id="demoslide2"></span></p>
  </div>
		</div>
		</small>


	<small>
	<div class="form-group">
	<input type="submit" value="Submit" class="btn btn-success btn-block" name="">
	</div>
	</small>





	</li>

        

        </ul>
  







      </div>
		</div>
		<div class="col-md-9">
			<div class="row">
				{% for i in featured %}
				<div class="col-md-3">
					<div>     
					<figure class="figure" style="border: 1px solid lightgrey;">
					<img src="{% static 'img/16.jpg' %}" class="figure-img img-fluid rounded" alt="Car image" style="width: 200px; height: 200px">
					<center>
					<center>
					<figcaption class="figure-caption">
					<h6>{{i.Product_title}}</h6>
					<hr>
					<h6>#{{i.price}}</h6>
					<p>{{i.vendor}}</p>
					<hr>
					<p>
					<span style="background-color: green; color: white;padding: 5px 5px; border-radius: 100%">
					<i class="fa fa-filter" style="font-size: 1.2em;"></i>
					</span>
					<span style="background-color: green; color: white;padding: 5px 5px; border-radius: 100%; margin-left: 10px; margin-right: 10px;">
					<i class="fa fa-heart" style="font-size: 1.2em;"></i>
					</span>
					<span style="background-color: green; color: white;padding: 5px 5px; border-radius: 100%">
					<i class="fa fa-shopping-cart" style="font-size: 1.2em;"></i>
					</span>
					</p>
					</figcaption>
					</center>
					</figure>
					</div>
				</div>

				{% endfor %}
			</div>
			
		</div>
	</div>
</div>




<script>
	brandlist = []
	subcategorylist = []
	// finalbrandlist = []
	// finalsubcategorylist = []

	{% for i in subcategory  %}
	subcategorylist.push('{{i.category}}' + ', ' + '{{i.subcategory}}')
	{% endfor %}

	{% for i in brand  %}
	brandlist.push('{{i.category}}' + ', ' + '{{i.subcategory}}' + ', ' + '{{i.name}}')
	{% endfor %}


	console.log(brandlist)
var selectcategory = document.querySelector("#selectcategory")
selectcategory.addEventListener('change', subCategory)

var selectsubcategory = document.querySelector("#selectsubcategory")
selectsubcategory.addEventListener('change', Brand)


function Brand(){
var categoryIndex = document.querySelector('#selectsubcategory').selectedIndex;
var selectedcategory = document.querySelector('#selectsubcategory').options[categoryIndex].text;
$('#selectbrandcategory').find('option').remove();

for(i=0;i<brandlist.length; i++){
data1 = brandlist[i].split(", ")
if(selectedcategory == data1[1]){
	console.log('yesss')
var option = document.createElement("option");
option.text = data1[2]
option.value = data1[2]
var select = document.querySelector("#selectbrandcategory")
select.appendChild(option);



}
// endif

}

// endfor
}




function subCategory(){
var categoryIndex = document.querySelector('#selectcategory').selectedIndex;
var selectedcategory = document.querySelector('#selectcategory').options[categoryIndex].text;
console.log(selectedcategory)
$('#selectsubcategory').find('option').remove();

for(i=0;i<subcategorylist.length; i++){
data1 = subcategorylist[i].split(", ")
if(selectedcategory == data1[0]){
	console.log('yesss')
var option = document.createElement("option");
// var option2 = document.createElement("option");

option.text = data1[1]
option.value = data1[1]
var select = document.querySelector("#selectsubcategory")
select.appendChild(option);



}
// endif

}

// endfor
}


</script>



{% endblock %}

project/templates/contact_us.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}

<style>
	body{
		background-color: rgb(245, 245, 245)
	}
</style>

<body>
<div class="container">
	<div class="row">
		<div class="col-md-5" style="background-color: white;">
			<p>
<small>				<h6>Address:</h6>
				<p>39A Ayilara Street Off Ojuelegba Road, Surulere Lagos.</p>
				<h6>Phone:</h6>
				<p>+234-07030330093</p>
				<h6>Website:</h6>
				<p>www.multitails.com</p>
				<h6>Email:</h6>
				<p>ask@multitails.com</p>
				
			</p>
			<hr>
			<h6>About Us</h6>
<p>	MultiTails is powered by Nzeeme Corporation, an organization that offer various products, solutions and services in ICT, teleccom, power, multimedia, home/office automation, education, surveillance security, digital marketing, software engineering, banking agency, etc.</p>

<p> Nzeeme Corporation is committed to empower businesses around the world with business automation, business registration, branding, enterprise solution, automated management system, digital marketing, e-commerce, software development,  etc.</p>

<p> Feel free to get in touch with us anytime for your business needs. Chat with us on WhatsApp for quick response. We are available 24/7 to ensure you enjoy maximum satisfaction. All the best!</p>
</small>	

	</div>



		<div class="col-md-7">
			<h6>CONTACT FORM</h6>

  <form action="/action_page.php">
    <div class="form-group">
      <label for="usr">Name:</label>
      <input type="text" class="form-control" id="usr" name="username">
    </div>
    <div class="form-group">
      <label for="pwd">Email:</label>
      <input type="email" class="form-control" id="pwd" name="password">
    </div>
    <div class="form-group">
      <label for="pwd">Subject:</label>
      <input type="text" class="form-control" id="pwd" name="password">
    </div>
	<div class="form-group">
	<label for="comment">Message:</label>
	<textarea class="form-control" rows="5" id="comment"></textarea>
	</div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>



		</div>
	</div>
</div>
</body>
{% endblock %}

project/templates/featuredproducts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}

<div class="container">
	<div class="row">
		<div class="col-md-3">
			<h6>ADVANCED SEARCH</h6>
   <div class="list-group list-group-flush">

      <ul class="list-group list-group-flush">
     <form method="POST" action="{% url 'index:other_filtered_items' %}"> {% csrf_token %}
     	
   

	<li class="list-group-item px-0">
		<small>
	<div class="form-group">
	<label for="sel1">ALL CATEGORIES:</label>
	<select class="form-control" id="selectcategory" name="category">
	<option>ALL CATEGORIES</option>
	{% for i in category %}

	<option>{{i}}</option>
	
	{% endfor %}
	</select>
	</div>
	</small>

	<div class="form-group">
	<small>
	<label for="sel1">ALL SUB CATEGORIES:</label>
	<select class="form-control" id="selectsubcategory" name="subcategory">
	<option>ALL SUB CATEGORIES</option>
	</select>
	</small>
	</div>

<small>
<div class="form-group">
<label for="sel1">ALL BRANDS:</label>
<select class="form-control" id="selectbrandcategory" name="brand">
<option>ALL BRANDS</option>
</select>
</div>
</small>

	<small>
	<div class="form-group">
	<input type="text" value="what are you looking for" class="form-control" name="search">
	</div>
	</small>


		<small>
		<div class="form-group">
		<label for="selectpostcode">Minimum Price</label>
		<div class="slidecontainer">
		<input type="range" min="1" max="100000000" value="50" class="slider" id="myRange" name='minprice'>
		<p>Value: <span id="demoslide"></span></p>
		</div>
		</div>
		</small>

		<small>
		<div class="form-group">
  <label for="selectpostcode">Maximum Price</label>
  <div class="slidecontainer">
  <input type="range" min="1" max="100000000" value="50" class="slider" id="myRange2" name="maxprice" >
  <p>Value: <span id="demoslide2"></span></p>
  </div>
		</div>
		</small>


	<small>
	<div class="form-group">
	<input type="submit" value="Submit" class="btn btn-success btn-block" name="">
	</div>
	</small>



  </form>

	</li>

        

        </ul>
  







      </div>
		</div>
		<div class="col-md-9">
			<div class="row">
				{% for i in featured %}
				<div class="col-md-3">
					<div>     
					<figure class="figure" style="border: 1px solid lightgrey;">
					<img src="{% static 'img/16.jpg' %}" class="figure-img img-fluid rounded" alt="Car image" style="width: 200px; height: 200px">
					<center>
					<center>
					<figcaption class="figure-caption">
					<h6>{{i.Product_title}}</h6>
					<hr>
					<h6>#{{i.price}}</h6>
					<p>{{i.vendor}}</p>
					<hr>
					<p>
					<span style="background-color: green; color: white;padding: 5px 5px; border-radius: 100%">
					<i class="fa fa-filter" style="font-size: 1.2em;"></i>
					</span>
					<span style="background-color: green; color: white;padding: 5px 5px; border-radius: 100%; margin-left: 10px; margin-right: 10px;">
					<i class="fa fa-heart" style="font-size: 1.2em;"></i>
					</span>
					<span style="background-color: green; color: white;padding: 5px 5px; border-radius: 100%">
					<i class="fa fa-shopping-cart" style="font-size: 1.2em;"></i>
					</span>
					</p>
					</figcaption>
					</center>
					</figure>
					</div>
				</div>

				{% endfor %}
			</div>
			
		</div>
	</div>
</div>




<script>
	brandlist = []
	subcategorylist = []
	// finalbrandlist = []
	// finalsubcategorylist = []

	{% for i in subcategory  %}
	subcategorylist.push('{{i.category}}' + ', ' + '{{i.subcategory}}')
	{% endfor %}

	{% for i in brand  %}
	brandlist.push('{{i.category}}' + ', ' + '{{i.subcategory}}' + ', ' + '{{i.name}}')
	{% endfor %}


	console.log(brandlist)
var selectcategory = document.querySelector("#selectcategory")
selectcategory.addEventListener('change', subCategory)

var selectsubcategory = document.querySelector("#selectsubcategory")
selectsubcategory.addEventListener('change', Brand)


function Brand(){
var categoryIndex = document.querySelector('#selectsubcategory').selectedIndex;
var selectedcategory = document.querySelector('#selectsubcategory').options[categoryIndex].text;
$('#selectbrandcategory').find('option').remove();

for(i=0;i<brandlist.length; i++){
data1 = brandlist[i].split(", ")
if(selectedcategory == data1[1]){
	console.log('yesss')
var option = document.createElement("option");
option.text = data1[2]
option.value = data1[2]
var select = document.querySelector("#selectbrandcategory")
select.appendChild(option);



}
// endif

}

// endfor
}




function subCategory(){
var categoryIndex = document.querySelector('#selectcategory').selectedIndex;
var selectedcategory = document.querySelector('#selectcategory').options[categoryIndex].text;
console.log(selectedcategory)
$('#selectsubcategory').find('option').remove();

for(i=0;i<subcategorylist.length; i++){
data1 = subcategorylist[i].split(", ")
if(selectedcategory == data1[0]){
	console.log('yesss')
var option = document.createElement("option");
var option2 = document.createElement("option");

option.text = data1[1]
option.value = data1[1]
option2.text = 'ALL SUB CATEGORIES'
option2.value = 'ALL SUB CATEGORIES'

var select = document.querySelector("#selectsubcategory")


select.appendChild(option);



}
// endif

}

// endfor
}


</script>



{% endblock %}

project/templates/todays_deal.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}

<div class="container">
	<div class="row">
		<div class="col-md-3">
			<h6>ADVANCED SEARCH</h6>
   <div class="list-group list-group-flush">

      <ul class="list-group list-group-flush">
     

	<li class="list-group-item px-0">
		<small>
	<div class="form-group">
	<label for="sel1">ALL CATEGORIES:</label>
	<select class="form-control" id="selectcategory">
	<option>ALL CATEGORIES</option>
	{% for i in category %}

	<option>{{i}}</option>
	
	{% endfor %}
	</select>
	</div>
	</small>

	<div class="form-group">
	<small>
	<label for="sel1">ALL CATEGORIES:</label>
	<select class="form-control" id="selectsubcategory">
	<option>ALL SUB CATEGORIES</option>
	</select>
	</small>
	</div>

<small>
<div class="form-group">
<label for="sel1">ALL BRANDS:</label>
<select class="form-control" id="selectbrandcategory">
<option>ALL BRANDS</option>
</select>
</div>
</small>

	<small>
	<div class="form-group">
	<input type="text" value="what are you looking for" class="form-control" name="">
	</div>
	</small>


		<small>
		<div class="form-group">
		<label for="selectpostcode">Minimum Price</label>
		<div class="slidecontainer">
		<input type="range" min="1" max="100000000" value="50" class="slider" id="myRange">
		<p>Value: <span id="demoslide"></span></p>
		</div>
		</div>
		</small>

		<small>
		<div class="form-group">
  <label for="selectpostcode">Maximum Price</label>
  <div class="slidecontainer">
  <input type="range" min="1" max="100000000" value="50" class="slider" id="myRange2">
  <p>Value: <span id="demoslide2"></span></p>
  </div>
		</div>
		</small>


	<small>
	<div class="form-group">
	<input type="submit" value="Submit" class="btn btn-success btn-block" name="">
	</div>
	</small>





	</li>

        

        </ul>
  







      </div>
		</div>
		<div class="col-md-9">
			<div class="row">
				{% for i in featured %}
				<div class="col-md-3">
					<div>     
					<figure class="figure" style="border: 1px solid lightgrey;">
					<img src="{% static 'img/16.jpg' %}" class="figure-img img-fluid rounded" alt="Car image" style="width: 200px; height: 200px">
					<center>
					<center>
					<figcaption class="figure-caption">
					<h6>{{i.Product_title}}</h6>
					<hr>
					<h6>#{{i.price}}</h6>
					<p>{{i.vendor}}</p>
					<hr>
					<p>
					<span style="background-color: green; color: white;padding: 5px 5px; border-radius: 100%">
					<i class="fa fa-filter" style="font-size: 1.2em;"></i>
					</span>
					<span style="background-color: green; color: white;padding: 5px 5px; border-radius: 100%; margin-left: 10px; margin-right: 10px;">
					<i class="fa fa-heart" style="font-size: 1.2em;"></i>
					</span>
					<span style="background-color: green; color: white;padding: 5px 5px; border-radius: 100%">
					<i class="fa fa-shopping-cart" style="font-size: 1.2em;"></i>
					</span>
					</p>
					</figcaption>
					</center>
					</figure>
					</div>
				</div>

				{% endfor %}
			</div>
			
		</div>
	</div>
</div>




<script>
	brandlist = []
	subcategorylist = []
	// finalbrandlist = []
	// finalsubcategorylist = []

	{% for i in subcategory  %}
	subcategorylist.push('{{i.category}}' + ', ' + '{{i.subcategory}}')
	{% endfor %}

	{% for i in brand  %}
	brandlist.push('{{i.category}}' + ', ' + '{{i.subcategory}}' + ', ' + '{{i.name}}')
	{% endfor %}


	console.log(brandlist)
var selectcategory = document.querySelector("#selectcategory")
selectcategory.addEventListener('change', subCategory)

var selectsubcategory = document.querySelector("#selectsubcategory")
selectsubcategory.addEventListener('change', Brand)


function Brand(){
var categoryIndex = document.querySelector('#selectsubcategory').selectedIndex;
var selectedcategory = document.querySelector('#selectsubcategory').options[categoryIndex].text;
$('#selectbrandcategory').find('option').remove();

for(i=0;i<brandlist.length; i++){
data1 = brandlist[i].split(", ")
if(selectedcategory == data1[1]){
	console.log('yesss')
var option = document.createElement("option");
option.text = data1[2]
option.value = data1[2]
var select = document.querySelector("#selectbrandcategory")
select.appendChild(option);



}
// endif

}

// endfor
}




function subCategory(){
var categoryIndex = document.querySelector('#selectcategory').selectedIndex;
var selectedcategory = document.querySelector('#selectcategory').options[categoryIndex].text;
console.log(selectedcategory)
$('#selectsubcategory').find('option').remove();

for(i=0;i<subcategorylist.length; i++){
data1 = subcategorylist[i].split(", ")
if(selectedcategory == data1[0]){
	console.log('yesss')
var option = document.createElement("option");
// var option2 = document.createElement("option");

option.text = data1[1]
option.value = data1[1]
var select = document.querySelector("#selectsubcategory")
select.appendChild(option);



}
// endif

}

// endfor
}


</script>



{% endblock %}